<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.9.3.0</Version>
    <Description>Shows which dungeon drip you are still missing from your Glamour Dresser and Armoire.</Description>
    <PackageProjectUrl>https://github.com/Spibane/DungeonDrip</PackageProjectUrl>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
